Remove TaskManager
bosagora/stoa pull request #158
Opened 2020-10-28 11:41 UTC by Geod24

There is no need for such a construct in Javascript,
as the runtime provides such a mechanism, unlike in D.

2020-10-28 11:42 UTC, Geod24 commented on src/Stoa.ts
> +                            success = await this.recoverBlock(block, height, expected_height);
I'm not 100% sure of this retry logic though. It matches the previous retry logic, but we should re-evaluate this in the future.

2020-10-29 03:24 UTC, AndrejMitrovic requested changes
Makes sense to me. Just a typo to fix.

2020-10-29 03:24 UTC, AndrejMitrovic commented on src/Stoa.ts
> +     * To ensure switft response time to Agora when our handlers are called,
```suggestion
     * To ensure swift response time to Agora when our handlers are called,
```

2020-10-29 03:29 UTC, Geod24 commented
Fixed typo, and extended commit description / title.

2020-10-29 03:35 UTC, merged