Trivial: Fix doc
bosagora/stoa pull request #308
Opened 2021-04-05 07:40 UTC by kchulj

2021-04-05 08:06 UTC, hewison-chris requested changes
Small change otherwise good.

2021-04-05 08:06 UTC, hewison-chris commented on src/modules/storage/LedgerStorage.ts
> +    The class that creates, inserts, and reads the ledger into the database.
You have an extra comma.

2021-04-05 08:10 UTC, kchulj commented on src/modules/storage/LedgerStorage.ts
> +    The class that creates, inserts, and reads the ledger into the database.
Fixed :)

2021-04-05 08:13 UTC, hewison-chris approved these changes
LGTM

2021-04-06 08:46 UTC, TrustHenry approved these changes

2021-04-06 08:46 UTC, merged